executor_url : "http://127.0.0.1:65157"
session_id : "d7f008750336f6373414847c80f9e3bb"
URL : "https://www.ea.com/en-gb/fifa/ultimate-team/web-app/"
EA_EMAIL : "EA@e.ea.com"
PLAYER : {
    "name": "Kante",
    "cost": 350000,
}
INCREASE_COUNT : 5
LOGIN_MANUALLY : True
USER : {
    "email": "",
    "password": "",
}
EMAIL_CREDENTIALS : {
    "email": "your_email@example.com",
    "password": "your_password",
}